name: build and testing

on:
  pull_request:
    branches:
      - temp
  push:
    branches:
      - temp

jobs:
  bulding:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        
    name: run build
    defaults:
      run:
        shell: bash
    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
         
       - name: installing dependencies
         run: yarn
       - name: installing dependencies
         run: yarn lint
       
       - name: running tests
         run: yarn test
        
       - name: running build
         run: yarn build
         

    
